import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { Sidebar } from "@/components/common/ui";
import Header from "@/components/common/ui/header/Header";

const poppins = Poppins({
  weight: ["400", "700"],
  style: ["normal"],
  display: "swap",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} h-screen w-full bg-gray-900 scroll-bar`}
      >
        <Toaster reverseOrder={false} position="top-center" />
        <Header />
        <Sidebar />
        {children}
      </body>
    </html>
  );
}
